### ISSUE TITLE
[Todo][Initialization] Intialize compiler-s20 organization

### ISSUE THREAD

**Issue by ianchen-tw** [compiler-s20/navigator#1]
- [ ] Clone repos
  - [ ] discussion board
  - [ ] invisible-hand
  - [x] website source
  - [x] website

- [ ] create teams
  - [ ] admin
  - [ ] teaching team
  - [ ] s20-students

- [ ] initalize discussion board
  - [x] issue tutorial
  - [x] labels
  - [x] issue templates
  - [ ] hook up with internal slack group
  - [ ] setup quick links
   
- [ ] update course website
  - [ ] style adjustment
  - [x] new google calendar
